### ISSUE TITLE
Controlled Widget

### ISSUE THREAD

**Issue by cstsortan** [eric-taix/fluid-nav-bar#17]
it would be much better if it could be refactored into a controlled widget with a property like currentIndex, where setState() would trigger the animation etc. and not internally through tap

**Comment by eric-taix** [comment]
I agree, many users would like to have a controller. I will try to take some time to add it in a future version.

**Comment by cstsortan** [comment]
I don't mean a controller, I mean a property that will react to changes reactively

**Comment by eric-taix** [comment]
But doesn't a controller would do this job? In Flutter controllers aim to control behaviour of the widget no?

**Comment by cstsortan** [comment]
Yes if that's easier to implement. But controlling the widget with a property through setState(), is the right way for a reactive framework, cause maybe the developer is using a global state container like redux, and doesn't want to expose the entire controller object, which is tightly coupled with the widget itself. Actually TextField should be working like that.
No matter how convenient a Controller is, it's a pain in big apps

**Comment by neffex97** [comment]
controller still not added? i need when user change page from drawer,bottombar also changed,so i think adding controller to this package would be good option
